---

- name: temporary
  hosts: all
  become: yes

  tasks:
    - name: creating a file
      file:
        path: /tmp/example.txt
        state: touch

    - name: install nginx
      apt:
        name: nginx
        state: present
